model_configs:
  model_name: PAC_Net
  pretrained: true
  rnn_type: gru
  rnn_hdim: 128
  v_loss: true
  warm_up: 32
  max_peo: 3

dataset_configs:
  dataset_root: /mnt/petrelfs/share_data/lisibo/NLOS/data_render_mot/ # fill your dataset path here!
  # dataset_root: ./dataset/real_shot_new
  # dataset_root: ../dataset/render
  data_type: real_shot
  train_ratio: 0.8
  route_len: 128
  # total_len: 250
  noise_factor: 0
  noisy: false
  max_peo: 3

loader_kwargs:
  num_workers: 8
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true

train_configs:
  project_name: my_project # fill your wandb project name here!
  # resume: True
  # resume_path: 2023_07_03_15_56_48/
  resume: false
  resume_path: None
  batch_size: 16
  seed: 1026
  device: cuda:0
  amp: true
  v_loss_alpha: 500
  x_loss_alpha: 1
  m_loss_alpha: 100

  loss_total_alpha: 1000

optim_kwargs:
  optimizer: AdamW
  lr: 3.0e-4
  weight_decay: 2.0e-3

schedule_configs:
  schedule_type: cosine
  max_epoch: 120
  cos_T: 70
  cos_iters: 1
  cos_mul: 2

distributed_configs:
  distributed: false
  gpu_ids: 0
  device_ids: 1
  world_size: 1
  local_rank: 0
  port: 6666

log_configs:
  log_dir: log # fill your log dir here!
  save_epoch_interval: 5
  snapshot_interval: 100